services:
  app:
    build: .
    container_name: vector-objects
    # command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    command: jupyter-lab --ip=0.0.0.0 --port=8889 --allow-root --no-browser -y
    ports:
      - 8889:8889
    volumes:
      - .:/code
  #   depends_on:
  #     - redis

  # redis:
  #   image: redis:alpine