services:
  app:
    build: .
    container_name: vector-objects
    # command: jupyter-lab --ip=0.0.0.0 --port=8889 --allow-root --no-browser -y
    tty: true
    environment:
      - PINECONE_API=${PINECONE_API}
    network_mode: host
    volumes:
      - .:/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
